<!-- new styles start here -->
<section class="section">
    <div class="container">
        <div class="col-md-12">
            <div class="col-md-12 no-gutter">
                <h2 class="text-center pb30">Fragebogen I</h2>
            </div>
            <div class="col-md-10 col-md-offset-1">
                <p class="text-center ">
                    Um Ihnen eine Empfehlung zur Verteilung Ihrer Finanzanlagen geben zu können, benötigen wir einige Angaben. Bitte beantworten Sie die folgenden sechs Fragen auf den Seiten 'Fragebogen I' bis 'Fragebogen VI'.
                </p>
                <hr>
            </div>
        </div>
        <div class="col-md-12">
            <h4 class="text-left pb15">Frage 1) </h4>
            <p class="text-lef pb30">
                Um Ihnen eine Empfehlung zur Verteilung Ihrer Finanzanlagen geben zu können, benötigen wir einige Angaben. Bitte beantworten Sie die folgenden sechs Fragen auf den Seiten 'Fragebogen I' bis 'Fragebogen VI'.
            </p>
        </div>
        <form id="submitform" action="questionnaire_proc.php" method="POST">
            <div class="col-md-12">
                <h5 class="pb15">a) Welchen Ertrag planten Sie mit dieser Investition zu erhalten?
            <div class="error">Bitte antworten Sie diese Frage</div>
        </h5>
                <div class="radio-bx pb15">
                    <div data-toggle="buttons" class="btn-group btn-group-justified fancy-radio-group">
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required> <span> weniger als 4%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required> <span>4-6%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required><span>6-8%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required><span>8-10%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required><span>mehr als 10%</span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <h5 class="pb15">b) Wie hoch schätzten Sie zu diesem Zeitpunkt den maximalen Ertrag?
        <div class="error active">Bitte antworten Sie diese Frage</div>        
        </h5>
                <div class="radio-bx pb15">
                    <div data-toggle="buttons" class="btn-group btn-group-justified fancy-radio-group">
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required> <span> weniger als 4%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required> <span>4-6%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required><span>6-8%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required><span>8-10%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options" required><span>mehr als 10%</span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="col-md-12"> required
                <h5 class="pb15">c) Wie hoch war Ihrer Meinung zum damaligen Zeitpunkt nach der grösste Verlust, der eintreten könnte?</h5>
                <div class="radio-bx pb15">
                    <div data-toggle="buttons" class="btn-group btn-group-justified fancy-radio-group">
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options"> <span> weniger als 4%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options"> <span>4-6%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options"><span>6-8%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options"><span>8-10%</span>
                        </label>
                        <label class="btn btn-fancy-radio text-xs text-no-transform clearfix"> <img src="data:image/gif;base64,R0lGODlhEgASAMQAAAAAAP////v7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAACH5BAEAABwALAAAAAASABIAAAV9ICeKymNtm/UoY8shEeUgBIE4VIS4ycUMgqBw0MAkRoiLQsgULi47jqTRrAoaEo6CArQyB5SSw1t1mBDkJuJESDMJm0zbHTRsKmi6YA0Z6x0QCxNdaQMTCwJTdAxZL0ppT1EcPT9VREYuCBIyBwQFNxQSki4LJhsaFA8LLiEAOw==" class="normal" /> <img src="data:image/gif;base64,R0lGODlhEgASANUAAAAAAP///xd/10yp+KLV/9ru/vv7+/r6+vn5+fj4+Pf39+/v7+7u7ufn5+bm5uXl5dra2tnZ2djY2MvLy8jIyL+/v729vbm5ubi4uLe3t7a2trKysrGxsa+vr66urq2trf///wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACH5BAEAACAALAAAAAASABIAAAaoQJBQ6JhoPh/NxDFsghgVjISBQDAkmArD2dhADoaw+BDhNIaMjUPMFj82W5AlIi4MBIJBQRyxgBwYYAYEeIUCBGEHGEUSYQWGhnsGEkYMYXeQeANhDEcIYZmGYQgfHZ8GoYVhCh8ZlgaYmZsGnRSNBo+hkhIUDxeChJCIBgcXD3J0jph6YhB+T2ptbW9xIF1f0mRmTgwWUgsICVcYFtVOD0YfHhgTx01BADs=" class="checked" />
                            <input type="radio" class="hidden" name="options"><span>mehr als 10%</span>
                        </label>
                    </div>
                </div>
            </div>
            <hr>
            <div class="col-md-12">
                <input type="submit" class="btn btn-primary btn-lg btn-block" value="Weiter">
            </div>
            <hr>
        </form>
    </div>
    <!-- container ends -->
</section>
<!-- new styles start here -->

